language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
env:
 - DJANGO_VERSION=1.4.10
 - DJANGO_VERSION=1.5.5
 - DJANGO_VERSION=1.6
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.4.10
install:
 - pip install -q Django==${DJANGO_VERSION} --use-mirrors
script: ./run.sh test
